# Generated by Django 5.2.6 on 2025-09-20 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_category_created_at_category_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
